AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cinema_matcher_serverless

  Sample SAM Template for cinema_matcher_serverless

Globals:
  Function:
    Timeout: 322

Resources:
  IMDBscraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: imdb_scraper/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        IMDBscraper:
          Type: Api
          Properties:
            Path: /imdb_scraper
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IMDBscraperApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  IMDBscraperFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt IMDBscraper.Arn
  IMDBscraperFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt IMDBscraperFunctionRole.Arn
