AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cinema_matcher_serverless

  Sample SAM Template for cinema_matcher_serverless

Globals:
  Function:
    Timeout: 322

Resources:
  IMDBScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: imdb_scraper/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        IMDBScraper:
          Type: Api
          Properties:
            Path: /imdb_scraper
            Method: get

Outputs:
  IMDBScraperApi:
    Description: "API Gateway endpoint URL for Prod stage for IMDB Scraper function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/IMDBScraper/"
  IMDBScraperFunction:
    Description: "IMDB Scraper Lambda Function ARN"
    Value: !GetAtt IMDBScraperFunction.Arn
  IMDBScraperFunctionIamRole:
    Description: "Implicit IAM Role created for the function that scrapes IMDB"
    Value: !GetAtt IMDBScraperFunctionRole.Arn
