name: Serverless SAM Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev libssl-dev curl software-properties-common
        python -m pip install --upgrade pip


        python -m pip install -r ./imdb_scraper/requirements.txt
        python -m pip install -r ./tests/requirements.txt
        python -m pip install -r ./dev-requirements.txt
    - name: flake8 Lint
      uses: py-actions/flake8@v1
      with:
        exclude: ".aws-sam"
        max-line-length: "99"
    - name: Run Unit Tests
      run: |
        python -m pytest tests/unit -vv
    - name: Deploy Lambdas via SAM
      uses: falnyr/aws-sam-deploy-action@v1.3.0
      env:
        TEMPLATE: 'template.yaml'
        AWS_STACK_NAME: "IMDBScraper"
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
